### ISSUE TITLE
Naming a function

### ISSUE THREAD

**Issue by rycastaneda** [anyTV/JS-conventions#1]
function foo () vs function foo()

The plugin HTML-CSS-JS prettifier does not correct the first one; corrects the second. Is the first one really the one we should follow?

**Comment by ravenjohn** [comment]
I don't advise using HTML-CSS-JS prettifier anymore. It doesn't always format the code in the most readable way. `function foo ()` is preferred than `function foo()` to indicate a visible separation between function name and parameters.
